CREATE TABLE "customers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" VARCHAR(255) NOT NULL,
  "username" VARCHAR(100) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "line_account" VARCHAR(255),
  "contact_name" VARCHAR(100),
  "phone" VARCHAR(50),
  "email" VARCHAR(255),
  "address" VARCHAR(255),
  "viewable_products" TEXT,
  "remark" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE order_status AS ENUM ('待確認', '已確認', '已出貨', '完成', '取消');
CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_number" VARCHAR(50) UNIQUE NOT NULL,
  "customer_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "product_quantity" INT NOT NULL,
  "product_unit" VARCHAR(50) NOT NULL,
  "total_price" DECIMAL(10,2) NOT NULL,
  "order_status" order_status NOT NULL DEFAULT '待確認',
  "remark" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "image_url" VARCHAR(255),
  "dm_url" VARCHAR(255),
  "min_order_qty" INT DEFAULT 1,
  "max_order_qty" INT,
  "product_unit" VARCHAR(50) NOT NULL,
  "shipping_time" TIMESTAMP,
  "special_date" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE operation_type AS ENUM ('新增', '刪除', '修改', '查詢');
CREATE TYPE user_type AS ENUM ('客戶', '管理員');
CREATE TABLE "logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_name" VARCHAR(255) NOT NULL,
  "operation_type" operation_type NOT NULL,
  "record_id" BIGINT,
  "operation_detail" TEXT,
  "performed_by" BIGINT NOT NULL,
  "user_type" user_type NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "permission_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level_name" VARCHAR(50) NOT NULL,
  "can_approve_orders" BOOLEAN NOT NULL DEFAULT FALSE,
  "can_edit_orders" BOOLEAN NOT NULL DEFAULT FALSE,
  "can_close_order_dates" BOOLEAN NOT NULL DEFAULT FALSE,
  "can_add_customer" BOOLEAN NOT NULL DEFAULT FALSE,
  "can_add_product" BOOLEAN NOT NULL DEFAULT FALSE,
  "can_add_personnel" BOOLEAN NOT NULL DEFAULT FALSE,
  "can_view_system_logs" BOOLEAN NOT NULL DEFAULT FALSE,
  "can_decide_product_view" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "administrators" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_account" VARCHAR(100) UNIQUE NOT NULL,
  "admin_password" VARCHAR(255) NOT NULL,
  "admin_name" VARCHAR(100) NOT NULL,
  "staff_no" VARCHAR(50),
  "permission_level_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "customers"."id" IS '客戶編號 (AUTO_INCREMENT)';
COMMENT ON COLUMN "customers"."company_name" IS '公司名稱';
COMMENT ON COLUMN "customers"."username" IS '客戶登入帳號';
COMMENT ON COLUMN "customers"."password" IS '客戶密碼(請雜湊後儲存)';
COMMENT ON COLUMN "customers"."line_account" IS 'LINE帳號(選填)';
COMMENT ON COLUMN "customers"."contact_name" IS '聯絡人姓名';
COMMENT ON COLUMN "customers"."phone" IS '聯絡電話';
COMMENT ON COLUMN "customers"."email" IS 'EMAIL';
COMMENT ON COLUMN "customers"."address" IS '地址';
COMMENT ON COLUMN "customers"."viewable_products" IS '可購買產品';
COMMENT ON COLUMN "customers"."remark" IS '備註';
COMMENT ON COLUMN "customers"."created_at" IS '新增時間';
COMMENT ON COLUMN "customers"."updated_at" IS '修改時間, ON UPDATE CURRENT_TIMESTAMP';

COMMENT ON COLUMN "orders"."id" IS '訂單編號 (AUTO_INCREMENT)';
COMMENT ON COLUMN "orders"."order_number" IS '訂單號';
COMMENT ON COLUMN "orders"."customer_id" IS '對應 customers.id';
COMMENT ON COLUMN "orders"."product_id" IS '對應 products.id';
COMMENT ON COLUMN "orders"."product_quantity" IS '產品數量';
COMMENT ON COLUMN "orders"."product_unit" IS '產品單位';
COMMENT ON COLUMN "orders"."total_price" IS '訂單總金額';
COMMENT ON COLUMN "orders"."order_status" IS '訂單狀態';
COMMENT ON COLUMN "orders"."remark" IS '備註';
COMMENT ON COLUMN "orders"."created_at" IS '新增時間';
COMMENT ON COLUMN "orders"."updated_at" IS '修改時間, ON UPDATE CURRENT_TIMESTAMP';

COMMENT ON COLUMN "products"."id" IS '產品編號 (AUTO_INCREMENT)';
COMMENT ON COLUMN "products"."name" IS '產品名稱';
COMMENT ON COLUMN "products"."description" IS '產品描述';
COMMENT ON COLUMN "products"."image_url" IS '產品圖片 URL 或檔名';
COMMENT ON COLUMN "products"."dm_url" IS '產品 DM(URL/檔名)';
COMMENT ON COLUMN "products"."min_order_qty" IS '最小下單數';
COMMENT ON COLUMN "products"."max_order_qty" IS '最大下單數(NULL 表示無上限)';
COMMENT ON COLUMN "products"."product_unit" IS '產品單位';
COMMENT ON COLUMN "products"."shipping_time" IS '出貨時間';
COMMENT ON COLUMN "products"."special_date" IS '特殊日期';
COMMENT ON COLUMN "products"."created_at" IS '新增時間';
COMMENT ON COLUMN "products"."updated_at" IS '修改時間, ON UPDATE CURRENT_TIMESTAMP';

COMMENT ON COLUMN "logs"."id" IS '日誌編號 (AUTO_INCREMENT)';
COMMENT ON COLUMN "logs"."table_name" IS '操作的表名稱';
COMMENT ON COLUMN "logs"."operation_type" IS '操作類型';
COMMENT ON COLUMN "logs"."record_id" IS '操作的記錄編號';
COMMENT ON COLUMN "logs"."operation_detail" IS '操作細節';
COMMENT ON COLUMN "logs"."performed_by" IS '操作人員 ID (對應 customers.id 或 administrators.id)';
COMMENT ON COLUMN "logs"."user_type" IS '操作人員類型';
COMMENT ON COLUMN "logs"."created_at" IS '操作時間';

COMMENT ON COLUMN "permission_levels"."id" IS '權限等級編號 (AUTO_INCREMENT)';
COMMENT ON COLUMN "permission_levels"."level_name" IS '權限等級名稱';
COMMENT ON COLUMN "permission_levels"."can_approve_orders" IS '是否可核定訂單';
COMMENT ON COLUMN "permission_levels"."can_edit_orders" IS '是否可修改訂單';
COMMENT ON COLUMN "permission_levels"."can_close_order_dates" IS '是否可關閉日期(使客戶無法下單)';
COMMENT ON COLUMN "permission_levels"."can_add_customer" IS '是否可新增客戶';
COMMENT ON COLUMN "permission_levels"."can_add_product" IS '是否可新增產品';
COMMENT ON COLUMN "permission_levels"."can_add_personnel" IS '是否可新增人員';
COMMENT ON COLUMN "permission_levels"."can_view_system_logs" IS '是否可查看系統日誌(LOG)';
COMMENT ON COLUMN "permission_levels"."can_decide_product_view" IS '是否可決定每個客戶可看到的產品';
COMMENT ON COLUMN "permission_levels"."created_at" IS '新增時間';
COMMENT ON COLUMN "permission_levels"."updated_at" IS '修改時間, ON UPDATE CURRENT_TIMESTAMP';

COMMENT ON COLUMN "administrators"."id" IS '管理員編號 (AUTO_INCREMENT)';
COMMENT ON COLUMN "administrators"."admin_account" IS '管理員帳號(登入用)';
COMMENT ON COLUMN "administrators"."admin_password" IS '管理員密碼(請雜湊後儲存)';
COMMENT ON COLUMN "administrators"."admin_name" IS '管理員姓名';
COMMENT ON COLUMN "administrators"."staff_no" IS '人員工號';
COMMENT ON COLUMN "administrators"."permission_level_id" IS '對應 permission_levels.id';
COMMENT ON COLUMN "administrators"."created_at" IS '新增時間';
COMMENT ON COLUMN "administrators"."updated_at" IS '修改時間, ON UPDATE CURRENT_TIMESTAMP';

ALTER TABLE "administrators" ADD FOREIGN KEY ("permission_level_id") REFERENCES "permission_levels" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "logs" ADD FOREIGN KEY ("performed_by") REFERENCES "customers" ("id");
ALTER TABLE "logs" ADD FOREIGN KEY ("performed_by") REFERENCES "administrators" ("id");
